// Fuente única de contenido estructurado del sitio (componentes, fichas, módulos IA, fases).

export const DSIP_PARTS = [
  { id: 'caja', n: 1, title: 'Caja de control e IA', icon: 'developer_board',
    text: 'El cerebro del nodo: un ESP32 controla las luces a 110 V, un switch PoE industrial alimenta las cámaras y una caja de IA sin ventilador analiza el video en el propio poste.',
    note: 'Sensores de puerta y vibración avisan a la central si alguien abre el gabinete.' },
  { id: 'bateria', n: 2, title: 'Respaldo LiFePO4', icon: 'battery_charging_full',
    text: 'Banco de litio-ferrofosfato de ≈ 1,3 kWh: semáforo, cámaras e IA siguen activos hasta 5 horas durante un corte de Corpoelec.',
    note: '4.000–6.000 ciclos de descarga profunda: 8 a 10 años de vida útil.' },
  { id: 'valla', n: 3, title: 'Valla LED publicitaria', icon: 'featured_video',
    text: 'Pantalla exterior de alto brillo con código QR para comprar pauta. Sus ingresos financian el mantenimiento del nodo.',
    note: 'En apagón se apaga sola para no consumir la batería.' },
  { id: 'ptz', n: 4, title: 'Cámara domo PTZ', icon: 'videocam',
    text: 'Domo de 8 MP con zoom óptico 36×. Cuando la IA detecta un evento, gira y enfoca el punto automáticamente para que el operador confirme.',
    note: 'Tecnología de baja luz para operar de noche y en apagones.' },
  { id: 'balas', n: 5, title: 'Cámaras fijas tipo bala', icon: 'photo_camera',
    text: 'Dos cámaras fijas vigilan los accesos de la intersección: lectura de placas (ANPR), conteo vehicular y detección de novedades viales.',
    note: 'Resistentes a la intemperie (IP66) y al vandalismo (IK10).' },
  { id: 'semaforo', n: 6, title: 'Semáforo ECO LED', icon: 'traffic',
    text: 'Cabezales LED que consumen más de 80 % menos que los semáforos tradicionales. Su estado se replica en tiempo real en el Mapa Vivo.',
    note: 'Preparado para ciclos adaptativos y “ola verde” para ambulancias (fase 7).' },
  { id: 'mic', n: 7, title: 'Micrófono de eventos', icon: 'graphic_eq',
    text: 'Clasifica sonidos (grito, disparo, vidrio roto, choque) en un búfer de 2 segundos en memoria. Nunca graba ni transmite audio.',
    note: 'Solo sale del poste una etiqueta: “grito · 0,86 · DSIP-04”.' },
  { id: 'antena', n: 8, title: 'Enlace P2P y 4G', icon: 'cell_tower',
    text: 'Radioenlace de 5 GHz o fibra hacia la central, con módem 4G multioperador de respaldo. Solo envía eventos de pocos KB.',
    note: 'Si el enlace cae, el nodo guarda los eventos y los sincroniza al volver.' },
  { id: 'poste', n: 9, title: 'Poste en L galvanizado', icon: 'architecture',
    text: 'Estructura de acero galvanizado con base de concreto, diseñada para soportar la valla y vientos fuertes.',
    note: 'Canalización interna para proteger el cableado del robo.' },
];

export const SPECS = {
  ptz: { title: 'Domo PTZ DarkFighter 8 MP', image: 'images/ptz.webp', items: [
    ['photo_camera', 'Sensor CMOS 1/1.8"', 'Escaneo progresivo para capturas nítidas y detalladas.'],
    ['zoom_in', 'Zoom óptico 36×', 'Más 16× digital para acercarse a detalles en áreas extensas.'],
    ['brightness_medium', 'DarkFighter 2.0', 'Excelente rendimiento con muy poca luz.'],
    ['filter_hdr', 'AWDR de 140 dB', 'Imagen clara aun con fuerte contraluz.'],
    ['center_focus_strong', 'Enfoque rápido', 'Autoenfoque de alta precisión al girar hacia una alerta.'],
    ['screen_rotation', 'Giroscopio', 'Imagen estable con viento o vibración del poste.'],
    ['shield', 'IP67 · IK10', 'Resistente al agua, al polvo y al vandalismo.'],
    ['water', 'NEMA 4X (opcional)', 'Resistencia a la corrosión en ambientes hostiles.'],
  ] },
  camera: { title: 'Cámara de videoanalítica Ultra HD', image: 'images/8.webp', items: [
    ['hd', 'Ultra HD', 'Máximo detalle para lectura de placas y conteo.'],
    ['filter_hdr', 'Procesador de imagen con IA', 'Reducción de ruido para imágenes limpias de noche.'],
    ['light_mode', 'Luz híbrida inteligente', 'Infrarrojo, luz blanca o híbrida según la escena.'],
    ['brightness_medium', 'WDR de 130 dB', 'Nitidez con contraluz fuerte.'],
    ['mic', 'Entrada de audio', 'Permite detectar excepciones de audio (Nivel 0 de IA).'],
    ['notification_important', 'Puertos de alarma', 'Integración con sensores perimetrales.'],
    ['shield', 'IP66 · IK10', 'Resistencia a intemperie y vandalismo.'],
  ] },
  semaforo: { title: 'Semáforo inteligente ECO LED', image: 'images/semaforo.webp', items: [
    ['eco', '−80 % de consumo', 'Frente a semáforos incandescentes o halógenos.'],
    ['traffic', 'Estado en tiempo real', 'Cada cambio de luz se refleja en el Mapa Vivo.'],
    ['directions_walk', 'Cruce peatonal', 'Preparado para extender el tiempo a personas mayores.'],
    ['emergency', 'Prioridad de emergencia', 'Ola verde para ambulancias y bomberos (fase 7).'],
    ['battery_charging_full', 'Sigue en apagón', 'Alimentado por el banco LiFePO4 del nodo.'],
    ['psychology', 'Ciclos adaptativos', 'Ajuste según el conteo vehicular de las cámaras.'],
  ] },
  pantalla: { title: 'Valla LED exterior', image: 'images/pantalla.webp', items: [
    ['hd', 'Pixel pitch fino', 'Legible a plena luz del sol.'],
    ['light_mode', 'Brillo adaptativo', 'Sensores ajustan los nits de día y de noche.'],
    ['thermostat', 'Chasis IP65', 'Hermético al polvo y al agua, apto para el calor de los llanos.'],
    ['qr_code_2', 'Pauta por QR', 'El anunciante compra y sube su contenido desde el teléfono.'],
    ['campaign', 'Mensajes de servicio', 'Rutas alternas, alertas de crecidas y avisos de Protección Civil.'],
    ['power_off', 'Modo apagón', 'Se apaga sola para proteger la batería del nodo.'],
  ] },
  edge: { title: 'Caja IA en el poste (Panoptes Vital)', image: null, icon: 'memory', items: [
    ['memory', 'Cómputo de IA industrial', 'Clase Jetson Orin NX 16 GB o RK3588 + Hailo-8.'],
    ['thermostat', 'Sin ventilador', 'Opera de −20 a 70 °C dentro del gabinete al sol.'],
    ['bolt', '≈ 15 W de consumo', 'Baja a 2–5 cuadros por segundo en apagón.'],
    ['cloud_off', 'Funciona sin internet', 'Procesa localmente y guarda eventos si cae el enlace.'],
    ['mic_off', 'Audio sin grabación', 'Clasifica y descarta; nunca almacena conversaciones.'],
    ['sync', 'Actualizable', 'Nuevos modelos se instalan de forma remota y firmada.'],
  ] },
  antena: { title: 'Enlace Ubiquiti P2P', image: 'images/antena.webp', items: [
    ['settings_input_antenna', '5,1–5,8 GHz', 'Espectro optimizado para evitar interferencias.'],
    ['signal_cellular_alt', 'Alta ganancia', 'Enlaces estables de largo alcance hacia la central.'],
    ['settings_ethernet', 'MIMO 2×2', 'Doble polarización para velocidad y robustez.'],
    ['air', 'Resistente al viento', 'Mantiene la alineación con cargas de viento elevadas.'],
  ] },
  cpu: { title: 'Servidor de procesamiento', image: 'images/cpu.webp', items: [
    ['developer_board', 'Xeon multinúcleo', 'Decodificación de múltiples flujos de video.'],
    ['memory', '128 GB RAM ECC', 'Estabilidad para operación 24/7.'],
    ['storage', 'NVMe', 'Lectura y escritura inmediata de eventos y capturas ANPR.'],
    ['smart_toy', 'GPU de inferencia', 'Para IA sobre cámaras comerciales se recomienda el servidor GPU del addon.'],
    ['power', 'Fuente redundante', 'Operación ininterrumpida del hardware.'],
  ] },
  videowall: { title: 'Video wall de control', image: 'images/videowall.webp', items: [
    ['grid_view', 'Sin bisel', 'LED Fine Pitch COB P1.5: imagen continua, sin cortes.'],
    ['brightness_high', '1.000 nits HDR', 'Visibilidad perfecta en la sala de control.'],
    ['schedule', 'Operación 24/7', 'Diseñado para misión crítica.'],
    ['developer_board', 'Procesador Novastar', 'Ventanas, zonas ampliadas y ruteo flexible de cámaras.'],
  ] },
};

export const C3I_PARTS = [
  { title: 'Video wall de monitoreo', icon: 'monitor', x: 42, y: 32,
    text: 'Pantalla LED Fine Pitch P1.5 sin bisel, 1.000 nits, para operación 24/7. Muestra el Mapa Vivo y las alertas priorizadas, no un mosaico de cámaras aburridas.',
    note: 'Ergonomía: consolas diseñadas para reducir la fatiga visual.' },
  { title: 'Servidores y cómputo', icon: 'dns', x: 64, y: 72,
    text: 'Rack cerrado de 42U con procesamiento local de video, base de datos de eventos y el motor Panoptes Core. Con el addon, suma un servidor GPU para la IA de la central.',
    note: 'Switches capa 3 y firewall protegen la red municipal.' },
  { title: 'Acceso y climatización', icon: 'fingerprint', x: 74, y: 35,
    text: 'Climatización redundante que mantiene el rack entre 18 y 21 °C, sensores de humedad e inundación y puerta reforzada con acceso biométrico.',
    note: 'Solo personal autorizado entra a la sala.' },
  { title: 'Estaciones de operadores', icon: 'desktop_windows', x: 22, y: 70,
    text: 'Puestos con GPU dedicada para mapas y video. El operador valida cada alerta con el video en vivo y despacha en un clic.',
    note: 'Cuentas nominales: cada acción queda en la bitácora inmutable.' },
  { title: 'Conexión con los nodos', icon: 'settings_input_antenna', x: 92, y: 45,
    text: 'Fibra o radioenlaces P2P traen los eventos y el video bajo demanda desde los nodos DSIP. Si un enlace cae, los nodos sincronizan al reconectarse.',
    note: 'Respaldo 4G multioperador para los nodos críticos.' },
];

export const GALLERY = [
  { img: 'images/semaforoiot.webp', title: 'Semáforos IoT en tiempo real', text: 'Cada intersección controlada por un nodo ESP32 se replica en el mapa: si el semáforo cambia a rojo en la calle, cambia a rojo en la pantalla central.' },
  { img: 'images/respaldo.webp', title: 'Respaldo eléctrico LiFePO4', text: 'Las baterías de litio mantienen semáforos y cámaras funcionando durante los apagones y avisan a la central el estado de carga.' },
  { img: 'images/central.webp', title: 'Sala de operaciones C3I', text: 'Todos los flujos del municipio en una sola sala: mapa, alertas priorizadas y despacho en un clic.' },
  { img: 'images/busquedaplaca.webp', title: 'Lectura de placas (ANPR)', text: 'Dos etapas de IA: primero localiza la placa y luego lee los caracteres. Resiste cambios de velocidad, iluminación y sombras. Las consultas a bases de vehículos solicitados requieren convenio.' },
  { img: 'images/busquedanocturna.webp', title: 'ANPR nocturno', text: 'La lectura de placas funciona de noche y durante apagones gracias a la iluminación infrarroja y al respaldo del nodo.' },
  { img: 'images/busquedarostro.webp', title: 'Búsqueda biométrica (con orden)', text: 'Comparación facial solo ante una orden de autoridad competente y con convenio para acceder a bases oficiales. Nunca en reuniones públicas ni en entornos escolares; siempre con verificación humana y registro en bitácora.' },
];

export const AI_CORE = [
  { code: 'IA-01', icon: 'personal_injury', title: 'Persona caída o desmayada',
    what: 'Persona que cae y queda inmóvil en el suelo más de 45–90 segundos.',
    ve: 'Golpes de calor, pensionados en colas de bancos, motorizado caído de noche, entrada del hospital.',
    filter: 'Personas sentadas en el brocal, mecánicos bajo un carro (zonas de exclusión) y personas en situación de calle, que se derivan a servicios sociales.' },
  { code: 'IA-02', icon: 'car_crash', title: 'Novedades viales',
    what: 'Choques, moto caída, vehículo detenido en la intersección, contrasentido y peatón en la calzada.',
    ve: 'Accidentes de motorizados e intersecciones sin semáforo durante los apagones.',
    filter: 'Doble fila en horario de carga y descarga, según reglas por zona.' },
  { code: 'IA-03', icon: 'local_fire_department', title: 'Humo e incendio',
    what: 'Humo y llamas en la vía, terrenos baldíos y vegetación.',
    ve: 'Quemas de vegetación en temporada seca y de cañaverales en zonas agrícolas.',
    filter: 'Parrillas de ventas de comida, quema menor de basura, polvo, neblina y escapes diésel: exige humo persistente y creciente.' },
  { code: 'IA-04', icon: 'shield_lock', title: 'Anti-sabotaje del nodo',
    what: 'Cámara tapada, girada o desenfocada; gabinete abierto; vibración o escalada del poste; batería desconectada.',
    ve: 'Robo de baterías y cable: protege directamente la inversión.',
    filter: 'Telarañas e insectos frente al infrarrojo, lluvia fuerte en el lente y pájaros.' },
  { code: 'IA-05', icon: 'graphic_eq', title: 'Gritos, disparos y vidrios',
    what: 'Gritos de auxilio, detonaciones, rotura de vidrios, impactos y frenazos.',
    ve: 'Robos a mano armada y riñas nocturnas cerca de licorerías.',
    filter: 'Cohetones y fuegos artificiales (diciembre, fiestas patronales, béisbol), escapes de moto, cornetas y recreos escolares. Nunca graba audio.' },
  { code: 'IA-06', icon: 'groups', title: 'Aglomeraciones y multitudes',
    what: 'Densidad de personas, flujo, estampidas, colas y aforo excedido.',
    ve: 'Peregrinaciones y fiestas patronales, ferias, salidas de colegios, terminal y colas en bancos o estaciones de servicio.',
    filter: 'Solo datos agregados: prohibido identificar a los asistentes de reuniones o manifestaciones.' },
];

export const AI_EXTRA = [
  { code: 'IA-07', icon: 'edit_note', title: 'Copiloto del operador', text: 'Redacta el parte de novedades de cada turno y permite buscar en lenguaje natural: “moto roja cerca de la farmacia entre 8 y 9 p. m.”. LLM local, sin nube.' },
  { code: 'IA-08', icon: 'low_priority', title: 'Motor de prioridad', text: 'Combina video, audio, botones SOS y reportes ciudadanos, ordena por gravedad y mide las falsas alarmas de cada nodo para evitar la fatiga del operador.' },
  { code: 'IA-09', icon: 'chat', title: 'WhatsApp con notas de voz', text: 'El ciudadano reporta por texto o nota de voz; la IA transcribe localmente, clasifica, ubica y crea un pin con la cámara más cercana.' },
  { code: 'IA-10', icon: 'construction', title: 'Ciudad mantenida', text: 'Detecta huecos, botes de aguas blancas o negras, basura acumulada y alumbrado apagado, y envía un reporte semanal a la alcaldía.' },
  { code: 'IA-11', icon: 'power_off', title: 'Mapa de apagones', text: 'Cada nodo registra cuándo se fue la luz y cuánto duró: un mapa por sector para planificar y gestionar con Corpoelec con datos reales.' },
  { code: 'IA-12', icon: 'emergency', title: 'Ola verde para ambulancias', text: 'Reconoce la sirena y el vehículo de emergencia y abre los semáforos de su ruta hacia el hospital.' },
  { code: 'IA-13', icon: 'pets', title: 'Animales en la vía', text: 'Ganado y caballos sueltos en troncales y accesos de noche: alerta a la central y aviso en la valla LED para los conductores.' },
  { code: 'IA-14', icon: 'person_search', title: 'Búsqueda humanitaria', text: 'Niño o adulto mayor extraviado en una feria o procesión: búsqueda por ropa y colores, sin biometría y solo con denuncia formal.' },
  { code: 'IA-15', icon: 'battery_alert', title: 'Mantenimiento predictivo', text: 'Vigila la salud de baterías, cámaras y enlaces para cambiar piezas antes de que un nodo se apague.' },
  { code: 'IA-16', icon: 'flood', title: 'Calles inundadas', text: 'Complementa los pluviómetros: detecta calles anegadas y cauces desbordados en la temporada de lluvias.' },
];

// Fases: meses relativos a la firma del contrato (negativos = antes de firmar).
export const ROADMAP = {
  start: -3, end: 36,
  phases: [
    { id: 0, kind: 'base', name: 'Validación y nodo demostrativo', short: 'Validación', from: -3, to: 0, when: 'Antes del contrato (3 meses)',
      goal: 'Demostrar resultados en la calle antes de comprometer la inversión completa.',
      items: ['Levantamiento técnico sin compromiso', '1 nodo DSIP demostrativo durante 90 días con IA de nivel 0–1', 'Borrador de ordenanza con anexo de IA responsable', 'Mesa técnica con cuerpos de seguridad y Protección Civil'],
      cost: '≈ $24.639,65 (1 nodo, descontable del piloto)', exit: 'Al menos 1 caso de respuesta asistida por IA documentado y ≥ 95 % de disponibilidad del nodo en apagones.' },
    { id: 1, kind: 'base', name: 'Central C3I', short: 'Central C3I', from: 1, to: 2, when: 'Meses 1–2',
      goal: 'Tener la sala de operaciones lista para recibir los nodos.',
      items: ['Adecuación física y eléctrica de la sala', 'Servidores, video wall, UPS y planta eléctrica', 'Instalación del núcleo Panoptes Core', 'Inicio de la capacitación de operadores'],
      cost: '$81.709,55 (+ planta eléctrica recomendada)', exit: 'Sala operativa 24/7 con operadores en formación.' },
    { id: 2, kind: 'base', name: '10 nodos DSIP', short: 'Nodos DSIP', from: 3, to: 5, when: 'Meses 3–5',
      goal: 'Encender la red de calle.',
      items: ['Izado de postes y montaje de vallas LED', 'Cámaras PTZ y bala con ANPR', 'Semáforos ECO LED y baterías LiFePO4', 'Enlaces P2P o fibra hacia la central'],
      cost: '$246.396,50', exit: '10/10 nodos en línea y autonomía en apagón verificada (≥ 4 h).' },
    { id: 3, kind: 'base', name: 'Fusión comercial', short: 'Fusión comercial', from: 6, to: 8, when: 'Meses 6–8',
      goal: 'Densificar el mapa con las cámaras que ya existen.',
      items: ['Adhesión incentivada (descuento en la patente) de licorerías, farmacias y comercios', 'Integración de colegios, liceos y el hospital', 'Convenios de cifrado y acceso con cada afiliado'],
      cost: 'Sin compra de cámaras; solo integración', exit: '≥ 60 cámaras comerciales integradas al Mapa Vivo.' },
    { id: 4, kind: 'base', name: 'Operación y concesión', short: 'Operación', from: 9, to: 36, when: 'Mes 9 en adelante (contrato a 15 años)',
      goal: 'Operar, mantener y autofinanciar el sistema.',
      items: ['Comercialización de la pauta en las vallas', 'Contrato de mantenimiento a 15 años', 'Integración con VEN 911 y 0-800-EXTORSIÓN (sujeta a convenio)', 'Informe público mensual de resultados'],
      cost: 'Vía A: $0 de operación · Vía B: tarifa fija mensual', exit: 'Ocupación publicitaria ≥ 40 % y disponibilidad del sistema ≥ 99 %.' },
    { id: 5, kind: 'ia', name: 'Panoptes Vital IA', short: 'IA Vital', from: 4, to: 12, when: 'Meses 4–12 (en paralelo)',
      goal: 'Sumar IA local que detecta emergencias sin depender de internet.',
      items: ['Meses 4–6: desarrollo del MVP y dataset local', 'Meses 6–9: IA en el poste (caídas, novedades, sabotaje, multitudes)', 'Meses 9–12: GPU en la central, copiloto y cámaras comerciales', 'Audio: al aprobarse el anexo de la ordenanza'],
      cost: '≈ $105.820 (primer despliegue)', exit: 'Precisión operativa ≥ 60 % a 90 días y menos de 5 falsas alarmas por nodo al día.' },
    { id: 6, kind: 'exp', name: 'Ciudadanía y protección civil', short: 'Ciudadanía', from: 12, to: 18, when: 'Meses 12–18',
      goal: 'Abrir el sistema al ciudadano y a la protección civil.',
      items: ['WhatsApp ciudadano con notas de voz (IA-09)', 'Puntos SOS con audio bidireccional en los postes', 'Alerta temprana hidrometeorológica y calles inundadas', 'Mapa de apagones (IA-11) y ciudad mantenida (IA-10)'],
      cost: '≈ $40.000–60.000 según módulos', exit: 'Tiempo de atención a reportes ciudadanos menor a 10 minutos.' },
    { id: 7, kind: 'exp', name: 'Ciudad inteligente y expansión', short: 'Expansión', from: 18, to: 36, when: 'Meses 18–36',
      goal: 'Pasar de la seguridad a la gestión urbana y replicar el modelo.',
      items: ['Semaforización adaptativa y ola verde para ambulancias', 'Dron de primera respuesta', 'Enlace satelital de respaldo (sujeto a habilitación)', 'Animales en la vía en troncales y línea agroindustrial', 'Réplica en otros municipios'],
      cost: 'Por módulo (p. ej., dron ≈ $25.000–40.000)', exit: 'Réplica en al menos un municipio adicional.' },
  ],
};
